export const USER_ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  PLATFORM_ADMIN: "PLATFORM_ADMIN",
  CITY_ADMIN: "CITY_ADMIN",
  DEPARTMENT_MANAGER: "DEPARTMENT_MANAGER",
  DISPATCHER: "DISPATCHER",
  TECHNICIAN: "TECHNICIAN",
  CITIZEN: "CITIZEN",
} as const;

export type UserRoleType = (typeof USER_ROLES)[keyof typeof USER_ROLES];
