/**
 * Synonym map indexed by category slug.
 * These expand the matching vocabulary — especially for local phrasing and common terms.
 * Add Bangla or transliterated terms as needed by someone who knows local phrasing.
 */

export const SYNONYMS: Record<string, string[]> = {
  // Road & Infrastructure
  "road-damage": [
    "pothole",
    "potholes",
    "crater",
    "crack",
    "cracked",
    "broken road",
    "road broken",
    "uneven road",
    "road surface",
    "asphalt",
    "tar",
    "bitumen",
    "bump",
    "bumpy",
    "depression",
    "sinkhole",
    "rut",
  ],
  "road-repair": ["pothole", "repair", "patch", "paving", "resurfacing", "fix road"],
  "footpath-damage": [
    "sidewalk",
    "pavement",
    "walkway",
    "footpath",
    "pedestrian path",
    "broken sidewalk",
    "cracked pavement",
    "tripping hazard",
    "trip",
  ],
  "manhole-cover": [
    "manhole",
    "sewer cover",
    "drain cover",
    "missing cover",
    "open manhole",
    "uncovered manhole",
    "cover missing",
  ],

  // Water
  "water-leakage": [
    "leak",
    "leaking",
    "leaks",
    "burst",
    "pipe burst",
    "water burst",
    "water pipe",
    "broken pipe",
    "flowing water",
    "water flowing",
    "puddle",
    "flooding",
    "flooded",
    "waterlogged",
    "seepage",
    "drip",
    "dripping",
    "gushing",
    "spilling",
    "water main",
  ],
  "water-supply": [
    "no water",
    "water shortage",
    "low pressure",
    "water pressure",
    "water cut",
    "supply cut",
    "water unavailable",
    "dry tap",
  ],
  "water-quality": [
    "dirty water",
    "brown water",
    "contaminated",
    "smell",
    "smelly water",
    "cloudy water",
    "rusty water",
    "muddy",
  ],

  // Electrical & Streetlights
  streetlight: [
    "street light",
    "streetlite",
    "streetlamp",
    "lamp post",
    "lamppost",
    "light pole",
    "dark street",
    "no light",
    "light out",
    "light off",
    "flickering light",
    "broken light",
    "dim light",
    "pole light",
  ],
  "electrical-issue": [
    "wire",
    "wires",
    "exposed wire",
    "hanging wire",
    "cable",
    "electric",
    "electricity",
    "power",
    "transformer",
    "sparking",
    "spark",
    "shock",
    "electrocution",
    "danger",
    "short circuit",
  ],

  // Waste & Sanitation
  "waste-collection": [
    "trash",
    "garbage",
    "rubbish",
    "refuse",
    "waste",
    "bin",
    "bins",
    "dustbin",
    "dumpster",
    "collection",
    "pickup",
    "uncollected",
    "overflowing",
    "overflow",
    "pile",
    "pileup",
    "dumping",
    "litter",
    "littering",
    "dirty",
    "filth",
    "filthy",
  ],
  "illegal-dumping": [
    "dump",
    "dumped",
    "illegal dump",
    "roadside dump",
    "construction waste",
    "debris",
    "rubble",
    "junk",
  ],

  // Drainage
  drainage: [
    "drain",
    "drains",
    "drainage",
    "clogged",
    "blocked",
    "blocked drain",
    "waterlogging",
    "flooding",
    "flood",
    "stagnant water",
    "standing water",
    "storm drain",
    "gutter",
    "culvert",
    "nala",
    "nallah",
  ],
  sewer: ["sewer", "sewage", "sewerage", "overflow", "smell", "stench", "sanitary", "sanitation"],

  // Parks & Environment
  "park-maintenance": [
    "park",
    "garden",
    "playground",
    "bench",
    "tree",
    "overgrown",
    "grass",
    "mowing",
    "green space",
  ],
  "tree-hazard": [
    "fallen tree",
    "uprooted",
    "dead tree",
    "leaning tree",
    "tree branch",
    "branch",
    "limb",
    "hanging branch",
  ],

  // Traffic & Signals
  "traffic-signal": [
    "traffic light",
    "signal",
    "red light",
    "green light",
    "traffic sign",
    "stop sign",
    "broken signal",
    "signal not working",
  ],
  "road-marking": [
    "marking",
    "lane marking",
    "zebra crossing",
    "crosswalk",
    "faded",
    "paint",
    "road paint",
  ],

  // General
  "noise-complaint": [
    "noise",
    "loud",
    "music",
    "construction noise",
    "honking",
    "disturbance",
    "noisy",
  ],
  "animal-control": [
    "stray",
    "dog",
    "dogs",
    "cat",
    "animal",
    "bite",
    "rabid",
    "dead animal",
    "carcass",
  ],
};

/**
 * Get synonyms for a given category slug.
 */
export function getSynonyms(slug: string): string[] {
  return SYNONYMS[slug] || [];
}
